/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Changelog: typeof import('./theme/components/Changelog.vue')['default']
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    FunctionInfo: typeof import('./theme/components/FunctionInfo.vue')['default']
    FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
    Home: typeof import('./theme/components/home.vue')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    Note: typeof import('./theme/components/Note.vue')['default']
    OcticonGitCommit16: typeof import('~icons/octicon/git-commit16')['default']
    OcticonGitPullRequestDraft16: typeof import('~icons/octicon/git-pull-request-draft16')['default']
    OcticonRocket16: typeof import('~icons/octicon/rocket16')['default']
  }
}
