// This file is generated by AI
<script setup lang="ts">
import { enableGesture } from 'comuse-shared'
import { onMounted, ref } from 'vue'

const gestureArea = ref<HTMLElement | null>(null)
const log = ref<string[]>([])
const box = ref<HTMLElement | null>(null)

const position = ref({ x: 0, y: 0 })
const startPosition = ref({ x: 0, y: 0 })

const addLog = (message: string) => {
  log.value.unshift(`${new Date().toLocaleTimeString()}: ${message}`)
  if (log.value.length > 5)
    log.value.pop()
}

const clamp = (value: number, min: number, max: number) => {
  return Math.min(Math.max(value, min), max)
}

onMounted(() => {
  if (!gestureArea.value || !box.value)
    return

  enableGesture(gestureArea.value)

  const boxWidth = box.value.offsetWidth
  const boxHeight = box.value.offsetHeight

  gestureArea.value.addEventListener('tap', (e: any) => {
    addLog(`Tap at (${e.clientX}, ${e.clientY})`)
  })

  gestureArea.value.addEventListener('press', () => {
    addLog('Press detected')
  })

  gestureArea.value.addEventListener('pressEnd', () => {
    addLog('Press ended')
  })

  gestureArea.value.addEventListener('panStart', (e: any) => {
    startPosition.value = {
      x: position.value.x,
      y: position.value.y,
    }
    const dx = Math.abs(e.clientX - e.startX)
    const dy = Math.abs(e.clientY - e.startY)
    const isVertical = dy > dx
    addLog(`Pan started, direction: ${isVertical ? 'vertical' : 'horizontal'}`)
  })

  gestureArea.value.addEventListener('pan', (e: any) => {
    if (box.value && gestureArea.value) {
      const dx = e.clientX - e.startX
      const dy = e.clientY - e.startY

      const containerWidth = gestureArea.value.offsetWidth
      const containerHeight = gestureArea.value.offsetHeight

      const maxX = containerWidth - boxWidth
      const maxY = containerHeight - boxHeight

      const newX = clamp(startPosition.value.x + dx, 0, maxX)
      const newY = clamp(startPosition.value.y + dy, 0, maxY)

      position.value = { x: newX, y: newY }

      box.value.style.transform = `translate(${newX}px, ${newY}px)`
    }
  })

  gestureArea.value.addEventListener('panEnd', (e: any) => {
    addLog(`Pan ended, ${e.isFlick ? 'with' : 'without'} flick`)

    if (e.isFlick) {
      const velocity = e.velocity
      const angle = Math.atan2(e.clientY - e.startY, e.clientX - e.startX)
      const vx = velocity * Math.cos(angle)
      const vy = velocity * Math.sin(angle)

      let currentX = position.value.x
      let currentY = position.value.y
      let currentVx = vx
      let currentVy = vy
      const friction = 0.95

      // 检查是否在浏览器环境中
      if (typeof window === 'undefined') return

      const animate = () => {
        if (!box.value || !gestureArea.value) return

        const containerWidth = gestureArea.value.offsetWidth
        const containerHeight = gestureArea.value.offsetHeight
        const maxX = containerWidth - boxWidth
        const maxY = containerHeight - boxHeight

        currentVx *= friction
        currentVy *= friction

        const nextX = currentX + currentVx * 16
        const nextY = currentY + currentVy * 16

        if (nextX <= 0 || nextX >= maxX)
          currentVx = 0
        if (nextY <= 0 || nextY >= maxY)
          currentVy = 0

        currentX = clamp(nextX, 0, maxX)
        currentY = clamp(nextY, 0, maxY)

        position.value = { x: currentX, y: currentY }
        box.value.style.transform = `translate(${currentX}px, ${currentY}px)`

        if ((Math.abs(currentVx) > 0.1 || Math.abs(currentVy) > 0.1) && !(currentVx === 0 && currentVy === 0))
          window?.requestAnimationFrame(animate)
      }

      window?.requestAnimationFrame(animate)
    }
  })

  gestureArea.value.addEventListener('flick', (e: any) => {
    addLog(`Flick detected with velocity: ${e.velocity.toFixed(2)}`)
  })
})
</script>

<template>
  <div class="flex flex-col items-center gap-4 p-4">
    <div
      ref="gestureArea"
      class="relative w-full h-300px bg-gray-100 rounded-lg overflow-hidden touch-none"
    >
      <div
        ref="box"
        class="absolute w-100px h-100px bg-blue-500 rounded-lg cursor-move"
      />
    </div>

    <div class="w-full space-y-2">
      <p class="font-bold">
        Gesture Log:
      </p>
      <div class="bg-gray-50 p-4 rounded-lg">
        <div
          v-for="(message, index) in log"
          :key="index"
          class="text-sm text-gray-600"
        >
          {{ message }}
        </div>
      </div>
    </div>

    <div class="w-full space-y-2">
      <p class="font-bold">
        Instructions:
      </p>
      <ul class="list-disc list-inside text-sm text-gray-600 space-y-1">
        <li>Tap anywhere in the gesture area</li>
        <li>Press and hold for press gesture</li>
        <li>Drag the blue box to move it (constrained within the area)</li>
        <li>Quickly release after panning for flick with inertia</li>
      </ul>
    </div>
  </div>
</template>
