name: Build Docs and Merge

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm run docs:build

      - name: Commit docs
        run: |
          # 配置 git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # 获取最新的 main 分支
          git fetch origin main:main

          # 切换到 main 分支
          git checkout main

          # 在合并之前重新生成 lock 文件
          pnpm install
          git add pnpm-lock.yaml
          git commit -m "chore: update pnpm-lock.yaml" || echo "No lock file changes"

          # 尝试合并
          if ! git merge --no-ff release -m "chore: merge docs from release"; then
            # 如果合并失败，使用 main 分支的 lock 文件
            git checkout --theirs pnpm-lock.yaml
            git add pnpm-lock.yaml
            git commit -m "chore: resolve merge conflicts in pnpm-lock.yaml"
          fi

          # 推送更改
          git push origin main
